<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ProSoft.HomeStack.Core.Default</AssemblyName>
    <AssemblyTitle>ProSoft.HomeStack.Core.Default</AssemblyTitle>
    <RootNamespace>ProSoft.HomeStack.Core.Default</RootNamespace>
  </PropertyGroup>

</Project>
