<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HomeStack.Core.Models</AssemblyName>
    <AssemblyTitle>HomeStack.Core.Models</AssemblyTitle>
    <RootNamespace>HomeStack.Core.Models</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeStack.Core.Default\HomeStack.Core.Default.csproj" />
  </ItemGroup>

</Project>
