using System.Diagnostics.CodeAnalysis;
using System.Net;
using ProSoft.HomeStack.Core.Models.Contracts;

namespace ProSoft.HomeStack.Core.Models;

/// <summary>
/// Class HomeStackInstance. This class cannot be inherited.
/// Implements the <see cref="IBaseObject" />
/// Implements the <see cref="System.IDisposable" />
/// Implements the <see cref="System.IAsyncDisposable" />
/// </summary>
/// <seealso cref="IBaseObject" />
/// <seealso cref="System.IDisposable" />
/// <seealso cref="System.IAsyncDisposable" />
public sealed class HomeStackInstance : IBaseObject, IDisposable, IAsyncDisposable
{
	/// <summary>
	/// Gets or sets the identifier.
	/// </summary>
	/// <value>The identifier.</value>
	public int Id { get; set; }

	/// <summary>
	/// Gets or sets the display name.
	/// </summary>
	/// <value>The display name.</value>
	public string DisplayName { get; set; } = "new hostinstance";

	/// <summary>
	/// Gets or sets the ip.
	/// </summary>
	/// <value>The ip.</value>
	public IPAddress IP { get; set; }

	/// <summary>
	/// Gets or sets the system identifier.
	/// </summary>
	/// <value>The system identifier.</value>
	public Guid SystemId { get; set; }

	/// <summary>
	/// Gets or sets the valid from.
	/// </summary>
	/// <value>The valid from.</value>
	public DateTimeOffset ValidFrom { get; set; } = Default.Date.MinDate;

	/// <summary>
	/// Gets or sets the valid to.
	/// </summary>
	/// <value>The valid to.</value>
	public DateTimeOffset ValidTo { get; set; } = Default.Date.MaxDate;

	/// <summary>
	/// Gets or sets the created at.
	/// </summary>
	/// <value>The created at.</value>
	public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

	/// <summary>
	/// Gets or sets the created by.
	/// </summary>
	/// <value>The created by.</value>
	public string CreatedBy { get; set; } = "system";

	/// <summary>
	/// Gets or sets the last updated at.
	/// </summary>
	/// <value>The last updated at.</value>
	public DateTimeOffset? LastUpdatedAt { get; set; }

	/// <summary>
	/// Gets or sets the last updated by.
	/// </summary>
	/// <value>The last updated by.</value>
	public string LastUpdatedBy { get; set; } = string.Empty;
	
	#region IDisposable implementation

	/// <summary>
	/// Releases the unmanaged resources.
	/// </summary>
	/// <autogeneratedoc />
	private void ReleaseUnmanagedResources()
	{
		// TODO release unmanaged resources here
	}

	/// <summary>
	/// Releases the managed resources.
	/// </summary>
	/// <autogeneratedoc />
	private void ReleaseManagedResources()
	{
		// TODO release managed resources here
	}

	/// <summary>
	/// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
	/// </summary>
	/// <autogeneratedoc />
	[ExcludeFromCodeCoverage]
	public void Dispose()
	{
		ReleaseUnmanagedResources();
		ReleaseManagedResources();
		GC.SuppressFinalize(this);
	}

	/// <summary>
	/// Performs application-defined tasks associated with freeing, releasing, or
	/// resetting unmanaged resources asynchronously.
	/// </summary>
	/// <returns>A Task&lt;ValueTask&gt; representing the asynchronous operation.</returns>
	/// <autogeneratedoc />
	[ExcludeFromCodeCoverage]
	public async ValueTask DisposeAsync()
	{
		await Task.CompletedTask;
		ReleaseUnmanagedResources();
		ReleaseManagedResources();
		GC.SuppressFinalize(this);
	}

	/// <summary>
	/// Finalizes an instance of the <see cref="HomeStackInstance"/> class.
	/// </summary>
	/// <autogeneratedoc />
	[ExcludeFromCodeCoverage]
	~HomeStackInstance()
	{
		ReleaseUnmanagedResources();
		ReleaseManagedResources();
	}

	#endregion
}
