<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HomeStack.Database</AssemblyName>
    <AssemblyTitle>HomeStack.Database</AssemblyTitle>
    <RootNamespace>HomeStack.Database</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeStack.Core.Models\HomeStack.Core.Models.csproj" />
    <ProjectReference Include="..\HomeStack.Core.Options\HomeStack.Core.Options.csproj" />
  </ItemGroup>

</Project>
