<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HomeStack.Core</AssemblyName>
    <AssemblyTitle>HomeStack.Core</AssemblyTitle>
    <RootNamespace>HomeStack.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Result" Version="10.1.0" />
  </ItemGroup>

</Project>
