<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HomeStack.Logic.Contracts</AssemblyName>
    <AssemblyTitle>HomeStack.Logic.Contracts</AssemblyTitle>
    <RootNamespace>HomeStack.Logic.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ProSoft.Result" Version="10.0.3-dev-260717115233" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeStack.Core.Models\HomeStack.Core.Models.csproj" />
  </ItemGroup>

</Project>
