<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HomeStack.Core.Infrastructure</AssemblyName>
    <AssemblyTitle>HomeStack.Core.Infrastructure</AssemblyTitle>
    <RootNamespace>HomeStack.Core.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeStack.Database.Infrastructure\HomeStack.Database.Infrastructure.csproj" />
  </ItemGroup>

</Project>
