<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HomeStack.Logic</AssemblyName>
    <AssemblyTitle>HomeStack.Logic</AssemblyTitle>
    <RootNamespace>HomeStack.Logic</RootNamespace>
  </PropertyGroup>

</Project>
